# Exercise 18 - KeyError
d = {'Name': 'John', 'Surname': 'Smith'}
# print(d['Smith']) # KeyError
print(d['Surname'])